export const FETCHING_PEOPLE_REQUEST = "FETCHING_PEOPLE_REQUEST";
export const FETCHING_PEOPLE_SUCCESS = "FETCHING_PEOPLE_SUCCESS";
export const FETCHING_PEOPLE_FAILURE = "FETCHING_PEOPLE_FAILURE";
export const FETCHING_PEOPLE_REFRESH = "FETCHING_PEOPLE_REFRESH";
export const FETCHING_PEOPLE_LOAD_MORE = "FETCHING_PEOPLE_LOAD_MORE";
